runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app
runtime_config:
   python_version: 3
env_variables:
   SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://root:chotot-cahopteam@/db?charset=utf8mb4&unix_socket=/cloudsql/chotot-recommendersys:asia-east1:chotot-db
   LANG: 'vi_VN.UTF-8'
beta_settings:
   cloud_sql_instances: chotot-recommendersys:asia-east1:chotot-db
